# Global settings applied to the whole site
[build]
  publish = "host-app/dist"
  command = "pnpm install && pnpm build"

# CORS headers for all sites
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"

# Handle client-side routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
